package web

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strconv"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"mergence/internal/config"
	"mergence/internal/logging"
	"mergence/internal/orchestrator"
	"mergence/internal/provider"
)

// newTestServer 起一个完整的服务（随机端口），返回 server 与 baseURL。
func newTestServer(t *testing.T, mutate func(*config.Config)) (*Server, string) {
	t.Helper()
	lg, err := logging.New("error", t.TempDir(), 200, 8)
	if err != nil {
		t.Fatal(err)
	}
	// LIFO：先注册的 Close 后执行——Shutdown 完才关日志文件，
	// 否则 Windows 上文件句柄未释放，TempDir 清理会失败。
	t.Cleanup(func() { _ = lg.Close() })

	cfgPath := filepath.Join(t.TempDir(), "mergence.json")
	cfg := config.Default()
	if mutate != nil {
		mutate(cfg)
	}
	reg := provider.NewRegistry(lg)
	orch := orchestrator.New(t.TempDir(), lg)
	s := New(lg, orch, reg, t.TempDir())
	s.SetConfig(cfg, cfgPath)
	port, err := s.Start()
	if err != nil {
		t.Fatalf("启动失败：%v", err)
	}
	t.Cleanup(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		s.Shutdown(ctx)
	})
	return s, "http://127.0.0.1:" + itoa(port)
}

// waitClosed 轮询等待端口关闭（旧监听器是异步优雅关闭的）。
func waitClosed(t *testing.T, port int) {
	t.Helper()
	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp",
			net.JoinHostPort("127.0.0.1", strconv.Itoa(port)), 300*time.Millisecond)
		if err != nil {
			return // 连不上 = 已关闭
		}
		conn.Close()
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatalf("端口 %d 在 3s 内未关闭", port)
}

// itoa 不引 strconv 就为了一个数字转换——测试文件里保持轻量。
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b [20]byte
	i := len(b)
	for n > 0 {
		i--
		b[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		b[i] = '-'
	}
	return string(b[i:])
}

func TestAccessKeyAutoGeneratedAndEnforced(t *testing.T) {
	s, base := newTestServer(t, nil)

	key := s.currentAccessKey()
	if key == "" {
		t.Fatal("normalize 应自动生成 access_key")
	}
	if len(key) != 32 {
		t.Errorf("Key 应为 32 位十六进制（128 位熵），得到 %d 位", len(key))
	}

	// 无 Key → 401（OpenAI 错误格式）
	resp, err := http.Get(base + "/v1/models")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Errorf("无 Key 访问 /v1/models 应 401，得到 %d", resp.StatusCode)
	}

	// 错 Key → 401
	req, _ := http.NewRequest("GET", base+"/v1/models", nil)
	req.Header.Set("Authorization", "Bearer wrong-key")
	resp2, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp2.Body.Close()
	if resp2.StatusCode != http.StatusUnauthorized {
		t.Errorf("错 Key 应 401，得到 %d", resp2.StatusCode)
	}

	// 正确 Key → 200（列表可为空，但接口本身应放行）
	req3, _ := http.NewRequest("GET", base+"/v1/models", nil)
	req3.Header.Set("Authorization", "Bearer "+key)
	resp3, err := http.DefaultClient.Do(req3)
	if err != nil {
		t.Fatal(err)
	}
	resp3.Body.Close()
	if resp3.StatusCode != http.StatusOK {
		t.Errorf("正确 Key 应 200，得到 %d", resp3.StatusCode)
	}

	// X-API-Key 头也应放行
	req4, _ := http.NewRequest("GET", base+"/v1/models", nil)
	req4.Header.Set("X-API-Key", key)
	resp4, err := http.DefaultClient.Do(req4)
	if err != nil {
		t.Fatal(err)
	}
	resp4.Body.Close()
	if resp4.StatusCode != http.StatusOK {
		t.Errorf("X-API-Key 应放行，得到 %d", resp4.StatusCode)
	}

	// 面板接口不受 Key 保护（本机控制面）
	resp5, err := http.Get(base + "/api/status")
	if err != nil {
		t.Fatal(err)
	}
	resp5.Body.Close()
	if resp5.StatusCode != http.StatusOK {
		t.Errorf("面板 /api/status 不应要求 Key，得到 %d", resp5.StatusCode)
	}
}

func TestAccessKeyRegenerate(t *testing.T) {
	s, base := newTestServer(t, nil)
	old := s.currentAccessKey()

	resp, err := http.Post(base+"/api/access-key/regenerate", "application/json", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("重新生成应 200，得到 %d", resp.StatusCode)
	}
	var d struct {
		OK        bool   `json:"ok"`
		AccessKey string `json:"access_key"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&d); err != nil {
		t.Fatal(err)
	}
	if !d.OK || d.AccessKey == "" || d.AccessKey == old {
		t.Fatalf("应返回新的非空 Key（old=%q new=%q）", old, d.AccessKey)
	}
	if s.currentAccessKey() != d.AccessKey {
		t.Error("服务端当前 Key 应立即更新")
	}

	// 旧 Key 立即失效
	req, _ := http.NewRequest("GET", base+"/v1/models", nil)
	req.Header.Set("Authorization", "Bearer "+old)
	resp2, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp2.Body.Close()
	if resp2.StatusCode != http.StatusUnauthorized {
		t.Errorf("旧 Key 应立即 401，得到 %d", resp2.StatusCode)
	}
}

func TestProxyRejectsNonManagedChannel(t *testing.T) {
	s, base := newTestServer(t, func(c *config.Config) {
		c.Embedded = append(c.Embedded, config.EmbeddedProvider{
			Name: "e1", DisplayName: "e1", Enabled: true,
			BaseURL: "http://127.0.0.1:1", Protocol: "chat", ModelPrefix: "e/",
		})
	})
	s.syncRegistry()

	resp, err := http.Get(base + "/api/channels/e1/upstream/overview")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusNotImplemented {
		t.Errorf("内嵌型渠道应 501 not_managed，得到 %d", resp.StatusCode)
	}

	resp2, err := http.Get(base + "/api/channels/nope/upstream/overview")
	if err != nil {
		t.Fatal(err)
	}
	resp2.Body.Close()
	if resp2.StatusCode != http.StatusNotFound {
		t.Errorf("不存在的渠道应 404，得到 %d", resp2.StatusCode)
	}
}

// TestAdminKeyAcceptsNativeChannel 原生（进程内）渠道同样有独立网关设置，
// 改密接口必须接受它。旧判据是 `up.Source != "managed"`，会把所有原生渠道挡成
// 501 not_managed —— 子进程模式移除后每个托管渠道都是原生型，那等于这个功能
// 整体失效。判据必须是 Hosted()。
func TestAdminKeyAcceptsNativeChannel(t *testing.T) {
	var gotPath, gotAuth atomic.Value
	up := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath.Store(r.URL.Path)
		gotAuth.Store(r.Header.Get("Authorization"))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = w.Write([]byte(`{"ok":true}`))
	}))
	defer up.Close()

	s, base := newTestServer(t, func(c *config.Config) {
		c.Managed = append(c.Managed, config.ManagedProvider{
			Name: "zc", DisplayName: "zc", Enabled: true,
			// Mode=native ⇒ FromManaged 产出的 Source 就是 SourceNative。
			Kind: "zcode", Mode: config.ModeNative,
			Route: &config.RouteSpec{APIKey: "old-key", ModelPrefix: "zcode-"},
		})
	})
	u := provider.FromManaged(s.currentConfig().Managed[0], up.URL, true, "")
	if u.Source != provider.SourceNative {
		t.Fatalf("Mode=native 应产出 SourceNative，得到 %q", u.Source)
	}
	u.RootURL = up.URL
	s.reg.Reload([]provider.Upstream{u})

	resp, err := http.Post(base+"/api/channels/admin-key", "application/json",
		strings.NewReader(`{"name":"zc","admin_key":"new-key"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotImplemented {
		t.Fatalf("原生渠道不该被判为 not_managed（得到 501）")
	}
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("改密应 200，得到 %d", resp.StatusCode)
	}
	// zcode 的管理 API 前缀是 /admin/api（不是 /panel/api）
	if got, _ := gotPath.Load().(string); got != "/admin/api/settings" {
		t.Errorf("应打到 zcode 的 /admin/api/settings，得到 %q", got)
	}
	if got, _ := gotAuth.Load().(string); got != "Bearer old-key" {
		t.Errorf("应用渠道旧 route key 鉴权，得到 %q", got)
	}
	// route key 是后台密码的真源：新值必须落盘到渠道配置
	var saved string
	for _, m := range s.currentConfig().Managed {
		if m.Name == "zc" && m.Route != nil {
			saved = m.Route.APIKey
		}
	}
	if saved != "new-key" {
		t.Errorf("route key 应同步为新值，得到 %q", saved)
	}
}

func TestProxyForwardsToManagedUpstream(t *testing.T) {
	// 假上游：模拟 wb2api 的 /panel/api/overview，校验 Bearer 注入
	var gotAuth atomic.Value
	up := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth.Store(r.Header.Get("Authorization"))
		if !strings.HasSuffix(r.URL.Path, "/panel/api/overview") {
			http.Error(w, "not found", http.StatusNotFound)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		_, _ = w.Write([]byte(`{"total":2,"healthy":2,"accounts":[{"uid":"u1","nickname":"A","credits":10}]}`))
	}))
	defer up.Close()
	// httptest 的 URL 形如 http://127.0.0.1:port；拆出根地址
	root := strings.TrimSuffix(up.URL, "/v1")

	s, base := newTestServer(t, func(c *config.Config) {
		c.Managed = append(c.Managed, config.ManagedProvider{
			Name: "m1", DisplayName: "m1", Enabled: true,
			PanelAPIPrefix: "/panel/api",
			Route: &config.RouteSpec{
				APIKey: "upstream-secret", ModelPrefix: "m/",
			},
		})
	})
	// 直接注册一个就绪的托管型上游（不真起子进程——代理不关心子进程，只关心地址）
	upstream := provider.FromManaged(
		s.currentConfig().Managed[0], root, true, "")
	// FromManaged 会拼 /v1 前缀；把它改回根地址 + 覆盖 RootURL
	upstream.BaseURL = root + "/v1"
	upstream.RootURL = root
	s.reg.Reload([]provider.Upstream{upstream})

	resp, err := http.Get(base + "/api/channels/m1/upstream/overview")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("代理应 200，得到 %d", resp.StatusCode)
	}
	var d struct {
		Total    int `json:"total"`
		Accounts []struct {
			UID string `json:"uid"`
		} `json:"accounts"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&d); err != nil {
		t.Fatal(err)
	}
	if d.Total != 2 || len(d.Accounts) != 1 || d.Accounts[0].UID != "u1" {
		t.Errorf("代理应原样透传上游响应，得到 %+v", d)
	}
	if got, _ := gotAuth.Load().(string); got != "Bearer upstream-secret" {
		t.Errorf("代理应注入渠道的 Bearer Key，得到 %q", got)
	}
}

func TestPortHotSwitch(t *testing.T) {
	s, base := newTestServer(t, nil)
	oldPort := s.Port()

	// 切到新端口
	body := strings.NewReader(`{"port": 0}`) // 0 = 动态，必定成功且不同于当前
	resp, err := http.Post(base+"/api/settings/port", "application/json", body)
	if err != nil {
		t.Fatal(err)
	}
	var d struct {
		OK      bool   `json:"ok"`
		BaseURL string `json:"base_url"`
		Port    int    `json:"port"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&d); err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if !d.OK || d.Port == 0 || d.Port == oldPort {
		t.Fatalf("应切换到新的动态端口，得到 port=%d（旧 %d）", d.Port, oldPort)
	}
	if s.Port() != d.Port {
		t.Errorf("Server.Port 应更新，得到 %d want %d", s.Port(), d.Port)
	}
	// 新端口上服务应可用
	resp2, err := http.Get(d.BaseURL + "/api/healthz")
	if err != nil {
		t.Fatalf("新端口不可访问：%v", err)
	}
	resp2.Body.Close()
	if resp2.StatusCode != http.StatusOK {
		t.Errorf("新端口 healthz 应 200，得到 %d", resp2.StatusCode)
	}
	// 旧端口应已关闭（异步优雅关闭，轮询等待）
	waitClosed(t, oldPort)

	// 配置应落盘
	if got := s.currentConfig().Ports.PanelPort; got != 0 {
		t.Errorf("动态模式 PanelPort 应为 0，得到 %d", got)
	}
}

func TestPortHotSwitchConflict(t *testing.T) {
	s, base := newTestServer(t, nil)

	// 占住一个端口
	blocker, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer blocker.Close()
	busy := blocker.Addr().(*net.TCPAddr).Port

	payload := strings.NewReader(`{"port": ` + itoa(busy) + `}`)
	resp, err := http.Post(base+"/api/settings/port", "application/json", payload)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusConflict {
		t.Errorf("占用端口应 409，得到 %d", resp.StatusCode)
	}
	// 原服务不受影响
	if s.Port() == busy {
		t.Error("失败时不应改变端口")
	}
	resp2, err := http.Get(base + "/api/healthz")
	if err != nil {
		t.Fatalf("原服务应继续可用：%v", err)
	}
	resp2.Body.Close()
}
