package config

import (
	"encoding/json"
	"strings"
	"testing"
)

func parseOne(t *testing.T, embedded []EmbeddedProvider) *Config {
	t.Helper()
	c := Default()
	c.Embedded = embedded
	raw, err := json.Marshal(c)
	if err != nil {
		t.Fatalf("序列化失败：%v", err)
	}
	got, _, err := Parse(raw)
	if err != nil {
		t.Fatalf("Parse 失败：%v", err)
	}
	return got
}

func TestModelListAcceptsBothForms(t *testing.T) {
	raw := []byte(`{
	  "embedded_providers": [{
	    "name": "x", "base_url": "https://a.b/v1",
	    "models": ["plain-id", {"id": "obj-id", "alias": "al", "context": 8192}]
	  }]
	}`)
	c, _, err := Parse(raw)
	if err != nil {
		t.Fatalf("Parse 失败：%v", err)
	}
	ms := c.Embedded[0].Models
	if len(ms) != 2 {
		t.Fatalf("模型数 = %d：%+v", len(ms), ms)
	}
	if ms[0].ID != "plain-id" || ms[0].Outward() != "plain-id" {
		t.Errorf("简写形式解析错误：%+v", ms[0])
	}
	if ms[1].ID != "obj-id" || ms[1].Outward() != "al" || ms[1].Context != 8192 {
		t.Errorf("完整形式解析错误：%+v", ms[1])
	}
}

func TestModelListDropsBlanksAndDuplicates(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{
		Name: "x", BaseURL: "https://a.b", Enabled: true,
		Models: ModelList{
			{ID: "a"}, {ID: ""}, {ID: "  "},
			{ID: "a"},             // 与首个重复
			{ID: "b", Alias: "a"}, // 对外名也叫 a → 重复
			{ID: "c"},
		},
	}})
	ms := c.Embedded[0].Models
	if len(ms) != 2 {
		t.Fatalf("去重后应剩 2 个，实际 %d：%+v", len(ms), ms)
	}
}

func TestPrefixAutoGenerated(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{
		{Name: "OpenRouter", BaseURL: "https://a.b", Enabled: true},
		{Name: "智谱 BigModel", BaseURL: "https://c.d", Enabled: true},
		{Name: "幻方量化", BaseURL: "https://e.f", Enabled: true},
	})
	if got := c.Embedded[0].ModelPrefix; got != "openrouter-" {
		t.Errorf("英文名应生成 slug 前缀，得到 %q", got)
	}
	// 中英混排：取其中的 ASCII 部分，比哈希可读得多
	if got := c.Embedded[1].ModelPrefix; got != "bigmodel-" {
		t.Errorf("中英混排应取 ASCII 片段，得到 %q", got)
	}
	// 纯中文取不出 ASCII → 退化为稳定哈希，但必须唯一且可路由
	zh := c.Embedded[2].ModelPrefix
	// 前缀不带尾斜杠（用户要求去掉 `/`），但要以 `-` 收尾保证边界可辨
	if !strings.HasSuffix(zh, "-") || strings.HasSuffix(zh, "/") ||
		!strings.HasPrefix(zh, "ch") {
		t.Fatalf("纯中文名应退化为 ch 前缀（以 - 收尾），得到 %q", zh)
	}
	if zh == c.Embedded[1].ModelPrefix {
		t.Fatalf("两个渠道的前缀不应相同：%q", zh)
	}
}

func TestPrefixCollisionDisablesLater(t *testing.T) {
	// 两条都显式指定同一个前缀：路由会歧义，必须禁掉后者而不是静默取第一个
	c := parseOne(t, []EmbeddedProvider{
		{Name: "a", BaseURL: "https://a.b", Enabled: true, ModelPrefix: "same"},
		{Name: "b", BaseURL: "https://c.d", Enabled: true, ModelPrefix: "same"},
	})
	if !c.Embedded[0].Enabled {
		t.Error("第一个渠道应保持启用")
	}
	if c.Embedded[1].Enabled {
		t.Error("前缀重复的渠道必须被禁用，否则请求会被送到错误的上游")
	}
	// 用户填的前缀语义不改，只补分隔符（`same` → `same-`），
	// 否则拼出来是 `samex-model`，前缀边界不可辨
	if c.Embedded[1].ModelPrefix != "same-" {
		t.Errorf("不应改写用户填的前缀语义：%q", c.Embedded[1].ModelPrefix)
	}
	// 存量配置里的尾斜杠要被剥掉，拼接时不再出现 `old/x` 这种形态
	c2 := parseOne(t, []EmbeddedProvider{
		{Name: "a", BaseURL: "https://a.b", Enabled: true, ModelPrefix: "old/"},
	})
	if got := c2.Embedded[0].ModelPrefix; got != "old-" {
		t.Errorf("存量配置的尾斜杠应被剥掉并补分隔符，得到 %q", got)
	}
	// 用户已自带分隔符的，不再多补
	c3 := parseOne(t, []EmbeddedProvider{
		{Name: "a", BaseURL: "https://a.b", Enabled: true, ModelPrefix: "wb-"},
	})
	if got := c3.Embedded[0].ModelPrefix; got != "wb-" {
		t.Errorf("已带 - 的前缀不应被改写：%q", got)
	}
}

func TestEnabledWithoutBaseURLDisabled(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{Name: "a", Enabled: true}})
	if c.Embedded[0].Enabled {
		t.Error("启用但没有 base_url 的渠道必须被禁用")
	}
}

func TestDefaultsApplied(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{
		Name: "a", BaseURL: "https://a.b/", Enabled: true,
	}})
	e := c.Embedded[0]
	if e.Protocol != "chat" {
		t.Errorf("protocol 默认 = %q", e.Protocol)
	}
	if e.Weight != 1 {
		t.Errorf("weight 默认 = %d", e.Weight)
	}
	if e.ModelSource != "auto" {
		t.Errorf("model_source 默认 = %q", e.ModelSource)
	}
	if e.DisplayName != "a" {
		t.Errorf("display_name 应回落为 name：%q", e.DisplayName)
	}
	if strings.HasSuffix(e.BaseURL, "/") {
		t.Errorf("base_url 结尾斜杠应被去掉：%q", e.BaseURL)
	}
	if e.HealthPath == "" {
		t.Error("health_path 应补默认值")
	}
	if e.TimeoutDuration().Seconds() != 120 {
		t.Errorf("超时默认 = %v", e.TimeoutDuration())
	}
}

func TestProtocolFallback(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{
		Name: "a", BaseURL: "https://a.b", Enabled: true, Protocol: "grpc",
	}})
	if c.Embedded[0].Protocol != "chat" {
		t.Errorf("未知协议应回落 chat，实际 %q", c.Embedded[0].Protocol)
	}
}

func TestRetriesClamped(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{
		Name: "a", BaseURL: "https://a.b", Enabled: true, Retries: 99,
	}})
	if c.Embedded[0].RetryCount() != 5 {
		t.Errorf("retries 应被钳制到 5，实际 %d", c.Embedded[0].RetryCount())
	}
}

func TestKeysTrimmedAndDedupedEmpty(t *testing.T) {
	c := parseOne(t, []EmbeddedProvider{{
		Name: "a", BaseURL: "https://a.b", Enabled: true,
		APIKeys: []string{"  sk-1  ", "", "   ", "sk-2"},
	}})
	keys := c.Embedded[0].APIKeys
	if len(keys) != 2 || keys[0] != "sk-1" || keys[1] != "sk-2" {
		t.Errorf("Key 清理结果 = %v", keys)
	}
}

func TestVersionUpgradedWithWarning(t *testing.T) {
	c, warns, err := Parse([]byte(`{"version": 1}`))
	if err != nil {
		t.Fatalf("Parse 失败：%v", err)
	}
	if c.Version != Version {
		t.Errorf("版本应升到 %d，实际 %d", Version, c.Version)
	}
	found := false
	for _, w := range warns {
		if strings.Contains(w, "已升级") {
			found = true
		}
	}
	if !found {
		t.Errorf("版本升级应给出提示，实际 %v", warns)
	}
}

func TestUnknownLogLevelFallsBack(t *testing.T) {
	c, warns, err := Parse([]byte(`{"log":{"level":"verbose"}}`))
	if err != nil {
		t.Fatalf("Parse 失败：%v", err)
	}
	if c.Log.Level != "info" {
		t.Errorf("非法级别应回落 info，实际 %q", c.Log.Level)
	}
	if len(warns) == 0 {
		t.Error("非法值应给出警告而不是静默")
	}
}

func TestMalformedJSONReportsError(t *testing.T) {
	if _, _, err := Parse([]byte(`{"log":`)); err == nil {
		t.Fatal("残缺 JSON 应当报错")
	}
}

func TestAutoPrefixStable(t *testing.T) {
	a := AutoPrefix("智谱 BigModel")
	b := AutoPrefix("智谱 BigModel")
	if a != b {
		t.Fatalf("同名的前缀必须稳定：%q vs %q", a, b)
	}
	if c := AutoPrefix("其他名字"); c == a {
		t.Errorf("不同名字不应得到相同前缀：%q", c)
	}
}
